(module
(import "vulkan.wasm32" "vkAcquireNextImage2KHR" (func $vkAcquireNextImage2KHR (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkAcquireNextImageKHR" (func $vkAcquireNextImageKHR (param i64) (param i64) (param i64) (param i64) (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkAllocateCommandBuffers" (func $vkAllocateCommandBuffers (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkAllocateDescriptorSets" (func $vkAllocateDescriptorSets (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkAllocateMemory" (func $vkAllocateMemory (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkBeginCommandBuffer" (func $vkBeginCommandBuffer (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkBindBufferMemory" (func $vkBindBufferMemory (param i64) (param i64) (param i64) (param i64) (result i32)))
(import "vulkan.wasm32" "vkBindImageMemory" (func $vkBindImageMemory (param i64) (param i64) (param i64) (param i64) (result i32)))
(import "vulkan.wasm32" "vkCmdBeginQuery" (func $vkCmdBeginQuery (param i64) (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdBeginRenderPass" (func $vkCmdBeginRenderPass (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdBindDescriptorSets" (func $vkCmdBindDescriptorSets (param i64) (param i32) (param i64) (param i32) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdBindIndexBuffer" (func $vkCmdBindIndexBuffer (param i64) (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkCmdBindPipeline" (func $vkCmdBindPipeline (param i64) (param i32) (param i64)))
(import "vulkan.wasm32" "vkCmdBindVertexBuffers" (func $vkCmdBindVertexBuffers (param i64) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdBlitImage" (func $vkCmdBlitImage (param i64) (param i64) (param i32) (param i64) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdClearAttachments" (func $vkCmdClearAttachments (param i64) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdClearColorImage" (func $vkCmdClearColorImage (param i64) (param i64) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdClearDepthStencilImage" (func $vkCmdClearDepthStencilImage (param i64) (param i64) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdCopyBuffer" (func $vkCmdCopyBuffer (param i64) (param i64) (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdCopyBufferToImage" (func $vkCmdCopyBufferToImage (param i64) (param i64) (param i64) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdCopyImage" (func $vkCmdCopyImage (param i64) (param i64) (param i32) (param i64) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdCopyImageToBuffer" (func $vkCmdCopyImageToBuffer (param i64) (param i64) (param i32) (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdCopyQueryPoolResults" (func $vkCmdCopyQueryPoolResults (param i64) (param i64) (param i32) (param i32) (param i64) (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkCmdDispatch" (func $vkCmdDispatch (param i64) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdDispatchIndirect" (func $vkCmdDispatchIndirect (param i64) (param i64) (param i64)))
(import "vulkan.wasm32" "vkCmdDraw" (func $vkCmdDraw (param i64) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdDrawIndexed" (func $vkCmdDrawIndexed (param i64) (param i32) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdDrawIndexedIndirect" (func $vkCmdDrawIndexedIndirect (param i64) (param i64) (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdDrawIndirect" (func $vkCmdDrawIndirect (param i64) (param i64) (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdEndQuery" (func $vkCmdEndQuery (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkCmdEndRenderPass" (func $vkCmdEndRenderPass (param i64)))
(import "vulkan.wasm32" "vkCmdExecuteCommands" (func $vkCmdExecuteCommands (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdFillBuffer" (func $vkCmdFillBuffer (param i64) (param i64) (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkCmdNextSubpass" (func $vkCmdNextSubpass (param i64) (param i32)))
(import "vulkan.wasm32" "vkCmdPipelineBarrier" (func $vkCmdPipelineBarrier (param i64) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdPushConstants" (func $vkCmdPushConstants (param i64) (param i64) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdResetEvent" (func $vkCmdResetEvent (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkCmdResetQueryPool" (func $vkCmdResetQueryPool (param i64) (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdResolveImage" (func $vkCmdResolveImage (param i64) (param i64) (param i32) (param i64) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdSetBlendConstants" (func $vkCmdSetBlendConstants (param i64) (param i32)))
(import "vulkan.wasm32" "vkCmdSetEvent" (func $vkCmdSetEvent (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkCmdSetScissor" (func $vkCmdSetScissor (param i64) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdSetStencilCompareMask" (func $vkCmdSetStencilCompareMask (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdSetStencilReference" (func $vkCmdSetStencilReference (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdSetStencilWriteMask" (func $vkCmdSetStencilWriteMask (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdSetViewport" (func $vkCmdSetViewport (param i64) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdUpdateBuffer" (func $vkCmdUpdateBuffer (param i64) (param i64) (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkCmdWaitEvents" (func $vkCmdWaitEvents (param i64) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkCmdWriteTimestamp" (func $vkCmdWriteTimestamp (param i64) (param i32) (param i64) (param i32)))
(import "vulkan.wasm32" "vkCreateBuffer" (func $vkCreateBuffer (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateBufferView" (func $vkCreateBufferView (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateCommandPool" (func $vkCreateCommandPool (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateComputePipelines" (func $vkCreateComputePipelines (param i64) (param i64) (param i32) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateDescriptorPool" (func $vkCreateDescriptorPool (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateDescriptorSetLayout" (func $vkCreateDescriptorSetLayout (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateDevice" (func $vkCreateDevice (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateEvent" (func $vkCreateEvent (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateFence" (func $vkCreateFence (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateFramebuffer" (func $vkCreateFramebuffer (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateGraphicsPipelines" (func $vkCreateGraphicsPipelines (param i64) (param i64) (param i32) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateImage" (func $vkCreateImage (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateImageView" (func $vkCreateImageView (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateInstance" (func $vkCreateInstance (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreatePipelineCache" (func $vkCreatePipelineCache (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreatePipelineLayout" (func $vkCreatePipelineLayout (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateQueryPool" (func $vkCreateQueryPool (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateRenderPass" (func $vkCreateRenderPass (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateSampler" (func $vkCreateSampler (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateSemaphore" (func $vkCreateSemaphore (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateShaderModule" (func $vkCreateShaderModule (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateSwapchainKHR" (func $vkCreateSwapchainKHR (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkCreateXlibSurfaceKHR" (func $vkCreateXlibSurfaceKHR (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkDestroyBuffer" (func $vkDestroyBuffer (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyBufferView" (func $vkDestroyBufferView (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyCommandPool" (func $vkDestroyCommandPool (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyDescriptorPool" (func $vkDestroyDescriptorPool (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyDescriptorSetLayout" (func $vkDestroyDescriptorSetLayout (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyDevice" (func $vkDestroyDevice (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyEvent" (func $vkDestroyEvent (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyFence" (func $vkDestroyFence (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyFramebuffer" (func $vkDestroyFramebuffer (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyImage" (func $vkDestroyImage (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyImageView" (func $vkDestroyImageView (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyInstance" (func $vkDestroyInstance (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyPipeline" (func $vkDestroyPipeline (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyPipelineCache" (func $vkDestroyPipelineCache (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyPipelineLayout" (func $vkDestroyPipelineLayout (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyQueryPool" (func $vkDestroyQueryPool (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyRenderPass" (func $vkDestroyRenderPass (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroySampler" (func $vkDestroySampler (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroySemaphore" (func $vkDestroySemaphore (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroyShaderModule" (func $vkDestroyShaderModule (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroySurfaceKHR" (func $vkDestroySurfaceKHR (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDestroySwapchainKHR" (func $vkDestroySwapchainKHR (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkDeviceWaitIdle" (func $vkDeviceWaitIdle (param i64) (result i32)))
(import "vulkan.wasm32" "vkEndCommandBuffer" (func $vkEndCommandBuffer (param i64) (result i32)))
(import "vulkan.wasm32" "vkEnumerateDeviceExtensionProperties" (func $vkEnumerateDeviceExtensionProperties (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkEnumerateDeviceLayerProperties" (func $vkEnumerateDeviceLayerProperties (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkEnumerateInstanceExtensionProperties" (func $vkEnumerateInstanceExtensionProperties (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkEnumerateInstanceLayerProperties" (func $vkEnumerateInstanceLayerProperties (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkEnumeratePhysicalDevices" (func $vkEnumeratePhysicalDevices (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkFlushMappedMemoryRanges" (func $vkFlushMappedMemoryRanges (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkFreeCommandBuffers" (func $vkFreeCommandBuffers (param i64) (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkFreeDescriptorSets" (func $vkFreeDescriptorSets (param i64) (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkFreeMemory" (func $vkFreeMemory (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkGetBufferMemoryRequirements" (func $vkGetBufferMemoryRequirements (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkGetDeviceGroupPresentCapabilitiesKHR" (func $vkGetDeviceGroupPresentCapabilitiesKHR (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkGetDeviceGroupSurfacePresentModesKHR" (func $vkGetDeviceGroupSurfacePresentModesKHR (param i64) (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkGetDeviceMemoryCommitment" (func $vkGetDeviceMemoryCommitment (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkGetDeviceQueue" (func $vkGetDeviceQueue (param i64) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkGetEventStatus" (func $vkGetEventStatus (param i64) (param i64) (result i32)))
(import "vulkan.wasm32" "vkGetFenceStatus" (func $vkGetFenceStatus (param i64) (param i64) (result i32)))
(import "vulkan.wasm32" "vkGetImageMemoryRequirements" (func $vkGetImageMemoryRequirements (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkGetImageSparseMemoryRequirements" (func $vkGetImageSparseMemoryRequirements (param i64) (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkGetImageSubresourceLayout" (func $vkGetImageSubresourceLayout (param i64) (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceFeatures" (func $vkGetPhysicalDeviceFeatures (param i64) (param i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceFormatProperties" (func $vkGetPhysicalDeviceFormatProperties (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceImageFormatProperties" (func $vkGetPhysicalDeviceImageFormatProperties (param i64) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceMemoryProperties" (func $vkGetPhysicalDeviceMemoryProperties (param i64) (param i32)))
(import "vulkan.wasm32" "vkGetPhysicalDevicePresentRectanglesKHR" (func $vkGetPhysicalDevicePresentRectanglesKHR (param i64) (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceProperties" (func $vkGetPhysicalDeviceProperties (param i64) (param i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceQueueFamilyProperties" (func $vkGetPhysicalDeviceQueueFamilyProperties (param i64) (param i32) (param i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceSparseImageFormatProperties" (func $vkGetPhysicalDeviceSparseImageFormatProperties (param i64) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceSurfaceCapabilitiesKHR" (func $vkGetPhysicalDeviceSurfaceCapabilitiesKHR (param i64) (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceSurfaceFormatsKHR" (func $vkGetPhysicalDeviceSurfaceFormatsKHR (param i64) (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceSurfacePresentModesKHR" (func $vkGetPhysicalDeviceSurfacePresentModesKHR (param i64) (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceSurfaceSupportKHR" (func $vkGetPhysicalDeviceSurfaceSupportKHR (param i64) (param i32) (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkGetPhysicalDeviceXlibPresentationSupportKHR" (func $vkGetPhysicalDeviceXlibPresentationSupportKHR (param i64) (param i32) (param i64) (param i64) (result i32)))
(import "vulkan.wasm32" "vkGetPipelineCacheData" (func $vkGetPipelineCacheData (param i64) (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkGetQueryPoolResults" (func $vkGetQueryPoolResults (param i64) (param i64) (param i32) (param i32) (param i32) (param i32) (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkGetRenderAreaGranularity" (func $vkGetRenderAreaGranularity (param i64) (param i64) (param i32)))
(import "vulkan.wasm32" "vkGetSwapchainImagesKHR" (func $vkGetSwapchainImagesKHR (param i64) (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkInvalidateMappedMemoryRanges" (func $vkInvalidateMappedMemoryRanges (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkMapMemory" (func $vkMapMemory (param i64) (param i64) (param i64) (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkMergePipelineCaches" (func $vkMergePipelineCaches (param i64) (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkQueueBindSparse" (func $vkQueueBindSparse (param i64) (param i32) (param i32) (param i64) (result i32)))
(import "vulkan.wasm32" "vkQueuePresentKHR" (func $vkQueuePresentKHR (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkQueueSubmit" (func $vkQueueSubmit (param i64) (param i32) (param i32) (param i64) (result i32)))
(import "vulkan.wasm32" "vkQueueWaitIdle" (func $vkQueueWaitIdle (param i64) (result i32)))
(import "vulkan.wasm32" "vkResetCommandBuffer" (func $vkResetCommandBuffer (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkResetCommandPool" (func $vkResetCommandPool (param i64) (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkResetDescriptorPool" (func $vkResetDescriptorPool (param i64) (param i64) (param i32) (result i32)))
(import "vulkan.wasm32" "vkResetEvent" (func $vkResetEvent (param i64) (param i64) (result i32)))
(import "vulkan.wasm32" "vkResetFences" (func $vkResetFences (param i64) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "vkSetEvent" (func $vkSetEvent (param i64) (param i64) (result i32)))
(import "vulkan.wasm32" "vkUnmapMemory" (func $vkUnmapMemory (param i64) (param i64)))
(import "vulkan.wasm32" "vkUpdateDescriptorSets" (func $vkUpdateDescriptorSets (param i64) (param i32) (param i32) (param i32) (param i32)))
(import "vulkan.wasm32" "vkWaitForFences" (func $vkWaitForFences (param i64) (param i32) (param i32) (param i32) (param i64) (result i32)))
(import "vulkan.wasm32" "vkCreateMetalSurfaceEXT" (func $vkCreateMetalSurfaceEXT (param i64) (param i32) (param i32) (param i32) (result i32)))
(import "vulkan.wasm32" "readMapped" (func $readMapped (param i64 i32 i32)))
(import "vulkan.wasm32" "writeMapped" (func $writeMapped (param i64 i32 i32)))
(memory (export "memory") 256)
(func (export "vkAcquireNextImage2KHR") (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkAcquireNextImage2KHR)
(func (export "vkAcquireNextImageKHR") (param i64) (param i64) (param i64) (param i64) (param i64) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 call $vkAcquireNextImageKHR)
(func (export "vkAllocateCommandBuffers") (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkAllocateCommandBuffers)
(func (export "vkAllocateDescriptorSets") (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkAllocateDescriptorSets)
(func (export "vkAllocateMemory") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkAllocateMemory)
(func (export "vkBeginCommandBuffer") (param i64) (param i32) (result i32) local.get 0 local.get 1 call $vkBeginCommandBuffer)
(func (export "vkBindBufferMemory") (param i64) (param i64) (param i64) (param i64) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkBindBufferMemory)
(func (export "vkBindImageMemory") (param i64) (param i64) (param i64) (param i64) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkBindImageMemory)
(func (export "vkCmdBeginQuery") (param i64) (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCmdBeginQuery)
(func (export "vkCmdBeginRenderPass") (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 call $vkCmdBeginRenderPass)
(func (export "vkCmdBindDescriptorSets") (param i64) (param i32) (param i64) (param i32) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 local.get 7 call $vkCmdBindDescriptorSets)
(func (export "vkCmdBindIndexBuffer") (param i64) (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCmdBindIndexBuffer)
(func (export "vkCmdBindPipeline") (param i64) (param i32) (param i64) local.get 0 local.get 1 local.get 2 call $vkCmdBindPipeline)
(func (export "vkCmdBindVertexBuffers") (param i64) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 call $vkCmdBindVertexBuffers)
(func (export "vkCmdBlitImage") (param i64) (param i64) (param i32) (param i64) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 local.get 7 call $vkCmdBlitImage)
(func (export "vkCmdClearAttachments") (param i64) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 call $vkCmdClearAttachments)
(func (export "vkCmdClearColorImage") (param i64) (param i64) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 call $vkCmdClearColorImage)
(func (export "vkCmdClearDepthStencilImage") (param i64) (param i64) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 call $vkCmdClearDepthStencilImage)
(func (export "vkCmdCopyBuffer") (param i64) (param i64) (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 call $vkCmdCopyBuffer)
(func (export "vkCmdCopyBufferToImage") (param i64) (param i64) (param i64) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 call $vkCmdCopyBufferToImage)
(func (export "vkCmdCopyImage") (param i64) (param i64) (param i32) (param i64) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 call $vkCmdCopyImage)
(func (export "vkCmdCopyImageToBuffer") (param i64) (param i64) (param i32) (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 call $vkCmdCopyImageToBuffer)
(func (export "vkCmdCopyQueryPoolResults") (param i64) (param i64) (param i32) (param i32) (param i64) (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 local.get 7 call $vkCmdCopyQueryPoolResults)
(func (export "vkCmdDispatch") (param i64) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCmdDispatch)
(func (export "vkCmdDispatchIndirect") (param i64) (param i64) (param i64) local.get 0 local.get 1 local.get 2 call $vkCmdDispatchIndirect)
(func (export "vkCmdDraw") (param i64) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 call $vkCmdDraw)
(func (export "vkCmdDrawIndexed") (param i64) (param i32) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 call $vkCmdDrawIndexed)
(func (export "vkCmdDrawIndexedIndirect") (param i64) (param i64) (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 call $vkCmdDrawIndexedIndirect)
(func (export "vkCmdDrawIndirect") (param i64) (param i64) (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 call $vkCmdDrawIndirect)
(func (export "vkCmdEndQuery") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkCmdEndQuery)
(func (export "vkCmdEndRenderPass") (param i64) local.get 0 call $vkCmdEndRenderPass)
(func (export "vkCmdExecuteCommands") (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 call $vkCmdExecuteCommands)
(func (export "vkCmdFillBuffer") (param i64) (param i64) (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 call $vkCmdFillBuffer)
(func (export "vkCmdNextSubpass") (param i64) (param i32) local.get 0 local.get 1 call $vkCmdNextSubpass)
(func (export "vkCmdPipelineBarrier") (param i64) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 local.get 7 local.get 8 local.get 9 call $vkCmdPipelineBarrier)
(func (export "vkCmdPushConstants") (param i64) (param i64) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 call $vkCmdPushConstants)
(func (export "vkCmdResetEvent") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkCmdResetEvent)
(func (export "vkCmdResetQueryPool") (param i64) (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCmdResetQueryPool)
(func (export "vkCmdResolveImage") (param i64) (param i64) (param i32) (param i64) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 call $vkCmdResolveImage)
(func (export "vkCmdSetBlendConstants") (param i64) (param i32) local.get 0 local.get 1 call $vkCmdSetBlendConstants)
(func (export "vkCmdSetEvent") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkCmdSetEvent)
(func (export "vkCmdSetScissor") (param i64) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCmdSetScissor)
(func (export "vkCmdSetStencilCompareMask") (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 call $vkCmdSetStencilCompareMask)
(func (export "vkCmdSetStencilReference") (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 call $vkCmdSetStencilReference)
(func (export "vkCmdSetStencilWriteMask") (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 call $vkCmdSetStencilWriteMask)
(func (export "vkCmdSetViewport") (param i64) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCmdSetViewport)
(func (export "vkCmdUpdateBuffer") (param i64) (param i64) (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 call $vkCmdUpdateBuffer)
(func (export "vkCmdWaitEvents") (param i64) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 local.get 7 local.get 8 local.get 9 local.get 10 call $vkCmdWaitEvents)
(func (export "vkCmdWriteTimestamp") (param i64) (param i32) (param i64) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCmdWriteTimestamp)
(func (export "vkCreateBuffer") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateBuffer)
(func (export "vkCreateBufferView") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateBufferView)
(func (export "vkCreateCommandPool") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateCommandPool)
(func (export "vkCreateComputePipelines") (param i64) (param i64) (param i32) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 call $vkCreateComputePipelines)
(func (export "vkCreateDescriptorPool") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateDescriptorPool)
(func (export "vkCreateDescriptorSetLayout") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateDescriptorSetLayout)
(func (export "vkCreateDevice") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateDevice)
(func (export "vkCreateEvent") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateEvent)
(func (export "vkCreateFence") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateFence)
(func (export "vkCreateFramebuffer") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateFramebuffer)
(func (export "vkCreateGraphicsPipelines") (param i64) (param i64) (param i32) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 call $vkCreateGraphicsPipelines)
(func (export "vkCreateImage") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateImage)
(func (export "vkCreateImageView") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateImageView)
(func (export "vkCreateInstance") (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkCreateInstance)
(func (export "vkCreatePipelineCache") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreatePipelineCache)
(func (export "vkCreatePipelineLayout") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreatePipelineLayout)
(func (export "vkCreateQueryPool") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateQueryPool)
(func (export "vkCreateRenderPass") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateRenderPass)
(func (export "vkCreateSampler") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateSampler)
(func (export "vkCreateSemaphore") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateSemaphore)
(func (export "vkCreateShaderModule") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateShaderModule)
(func (export "vkCreateSwapchainKHR") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateSwapchainKHR)
(func (export "vkCreateXlibSurfaceKHR") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateXlibSurfaceKHR)
(func (export "vkDestroyBuffer") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyBuffer)
(func (export "vkDestroyBufferView") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyBufferView)
(func (export "vkDestroyCommandPool") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyCommandPool)
(func (export "vkDestroyDescriptorPool") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyDescriptorPool)
(func (export "vkDestroyDescriptorSetLayout") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyDescriptorSetLayout)
(func (export "vkDestroyDevice") (param i64) (param i32) local.get 0 local.get 1 call $vkDestroyDevice)
(func (export "vkDestroyEvent") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyEvent)
(func (export "vkDestroyFence") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyFence)
(func (export "vkDestroyFramebuffer") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyFramebuffer)
(func (export "vkDestroyImage") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyImage)
(func (export "vkDestroyImageView") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyImageView)
(func (export "vkDestroyInstance") (param i64) (param i32) local.get 0 local.get 1 call $vkDestroyInstance)
(func (export "vkDestroyPipeline") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyPipeline)
(func (export "vkDestroyPipelineCache") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyPipelineCache)
(func (export "vkDestroyPipelineLayout") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyPipelineLayout)
(func (export "vkDestroyQueryPool") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyQueryPool)
(func (export "vkDestroyRenderPass") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyRenderPass)
(func (export "vkDestroySampler") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroySampler)
(func (export "vkDestroySemaphore") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroySemaphore)
(func (export "vkDestroyShaderModule") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroyShaderModule)
(func (export "vkDestroySurfaceKHR") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroySurfaceKHR)
(func (export "vkDestroySwapchainKHR") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkDestroySwapchainKHR)
(func (export "vkDeviceWaitIdle") (param i64) (result i32) local.get 0 call $vkDeviceWaitIdle)
(func (export "vkEndCommandBuffer") (param i64) (result i32) local.get 0 call $vkEndCommandBuffer)
(func (export "vkEnumerateDeviceExtensionProperties") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkEnumerateDeviceExtensionProperties)
(func (export "vkEnumerateDeviceLayerProperties") (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkEnumerateDeviceLayerProperties)
(func (export "vkEnumerateInstanceExtensionProperties") (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkEnumerateInstanceExtensionProperties)
(func (export "vkEnumerateInstanceLayerProperties") (param i32) (param i32) (result i32) local.get 0 local.get 1 call $vkEnumerateInstanceLayerProperties)
(func (export "vkEnumeratePhysicalDevices") (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkEnumeratePhysicalDevices)
(func (export "vkFlushMappedMemoryRanges") (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkFlushMappedMemoryRanges)
(func (export "vkFreeCommandBuffers") (param i64) (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkFreeCommandBuffers)
(func (export "vkFreeDescriptorSets") (param i64) (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkFreeDescriptorSets)
(func (export "vkFreeMemory") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkFreeMemory)
(func (export "vkGetBufferMemoryRequirements") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkGetBufferMemoryRequirements)
(func (export "vkGetDeviceGroupPresentCapabilitiesKHR") (param i64) (param i32) (result i32) local.get 0 local.get 1 call $vkGetDeviceGroupPresentCapabilitiesKHR)
(func (export "vkGetDeviceGroupSurfacePresentModesKHR") (param i64) (param i64) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkGetDeviceGroupSurfacePresentModesKHR)
(func (export "vkGetDeviceMemoryCommitment") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkGetDeviceMemoryCommitment)
(func (export "vkGetDeviceQueue") (param i64) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkGetDeviceQueue)
(func (export "vkGetEventStatus") (param i64) (param i64) (result i32) local.get 0 local.get 1 call $vkGetEventStatus)
(func (export "vkGetFenceStatus") (param i64) (param i64) (result i32) local.get 0 local.get 1 call $vkGetFenceStatus)
(func (export "vkGetImageMemoryRequirements") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkGetImageMemoryRequirements)
(func (export "vkGetImageSparseMemoryRequirements") (param i64) (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkGetImageSparseMemoryRequirements)
(func (export "vkGetImageSubresourceLayout") (param i64) (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkGetImageSubresourceLayout)
(func (export "vkGetPhysicalDeviceFeatures") (param i64) (param i32) local.get 0 local.get 1 call $vkGetPhysicalDeviceFeatures)
(func (export "vkGetPhysicalDeviceFormatProperties") (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 call $vkGetPhysicalDeviceFormatProperties)
(func (export "vkGetPhysicalDeviceImageFormatProperties") (param i64) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 call $vkGetPhysicalDeviceImageFormatProperties)
(func (export "vkGetPhysicalDeviceMemoryProperties") (param i64) (param i32) local.get 0 local.get 1 call $vkGetPhysicalDeviceMemoryProperties)
(func (export "vkGetPhysicalDevicePresentRectanglesKHR") (param i64) (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkGetPhysicalDevicePresentRectanglesKHR)
(func (export "vkGetPhysicalDeviceProperties") (param i64) (param i32) local.get 0 local.get 1 call $vkGetPhysicalDeviceProperties)
(func (export "vkGetPhysicalDeviceQueueFamilyProperties") (param i64) (param i32) (param i32) local.get 0 local.get 1 local.get 2 call $vkGetPhysicalDeviceQueueFamilyProperties)
(func (export "vkGetPhysicalDeviceSparseImageFormatProperties") (param i64) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 local.get 7 call $vkGetPhysicalDeviceSparseImageFormatProperties)
(func (export "vkGetPhysicalDeviceSurfaceCapabilitiesKHR") (param i64) (param i64) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkGetPhysicalDeviceSurfaceCapabilitiesKHR)
(func (export "vkGetPhysicalDeviceSurfaceFormatsKHR") (param i64) (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkGetPhysicalDeviceSurfaceFormatsKHR)
(func (export "vkGetPhysicalDeviceSurfacePresentModesKHR") (param i64) (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkGetPhysicalDeviceSurfacePresentModesKHR)
(func (export "vkGetPhysicalDeviceSurfaceSupportKHR") (param i64) (param i32) (param i64) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkGetPhysicalDeviceSurfaceSupportKHR)
(func (export "vkGetPhysicalDeviceXlibPresentationSupportKHR") (param i64) (param i32) (param i64) (param i64) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkGetPhysicalDeviceXlibPresentationSupportKHR)
(func (export "vkGetPipelineCacheData") (param i64) (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkGetPipelineCacheData)
(func (export "vkGetQueryPoolResults") (param i64) (param i64) (param i32) (param i32) (param i32) (param i32) (param i64) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 local.get 6 local.get 7 call $vkGetQueryPoolResults)
(func (export "vkGetRenderAreaGranularity") (param i64) (param i64) (param i32) local.get 0 local.get 1 local.get 2 call $vkGetRenderAreaGranularity)
(func (export "vkGetSwapchainImagesKHR") (param i64) (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkGetSwapchainImagesKHR)
(func (export "vkInvalidateMappedMemoryRanges") (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkInvalidateMappedMemoryRanges)
(func (export "vkMapMemory") (param i64) (param i64) (param i64) (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 local.get 5 call $vkMapMemory)
(func (export "vkMergePipelineCaches") (param i64) (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkMergePipelineCaches)
(func (export "vkQueueBindSparse") (param i64) (param i32) (param i32) (param i64) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkQueueBindSparse)
(func (export "vkQueuePresentKHR") (param i64) (param i32) (result i32) local.get 0 local.get 1 call $vkQueuePresentKHR)
(func (export "vkQueueSubmit") (param i64) (param i32) (param i32) (param i64) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkQueueSubmit)
(func (export "vkQueueWaitIdle") (param i64) (result i32) local.get 0 call $vkQueueWaitIdle)
(func (export "vkResetCommandBuffer") (param i64) (param i32) (result i32) local.get 0 local.get 1 call $vkResetCommandBuffer)
(func (export "vkResetCommandPool") (param i64) (param i64) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkResetCommandPool)
(func (export "vkResetDescriptorPool") (param i64) (param i64) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkResetDescriptorPool)
(func (export "vkResetEvent") (param i64) (param i64) (result i32) local.get 0 local.get 1 call $vkResetEvent)
(func (export "vkResetFences") (param i64) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 call $vkResetFences)
(func (export "vkSetEvent") (param i64) (param i64) (result i32) local.get 0 local.get 1 call $vkSetEvent)
(func (export "vkUnmapMemory") (param i64) (param i64) local.get 0 local.get 1 call $vkUnmapMemory)
(func (export "vkUpdateDescriptorSets") (param i64) (param i32) (param i32) (param i32) (param i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 call $vkUpdateDescriptorSets)
(func (export "vkWaitForFences") (param i64) (param i32) (param i32) (param i32) (param i64) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 local.get 4 call $vkWaitForFences)
(func (export "vkCreateMetalSurfaceEXT") (param i64) (param i32) (param i32) (param i32) (result i32) local.get 0 local.get 1 local.get 2 local.get 3 call $vkCreateMetalSurfaceEXT)
(func (export "readMapped") (param i64 i32 i32) local.get 0 local.get 1 local.get 2 call $readMapped)
(func (export "writeMapped") (param i64 i32 i32) local.get 0 local.get 1 local.get 2 call $writeMapped)
)
