// Code generated by scripts/generate.py; DO NOT EDIT.
package vulkan

/*
#include "bridge.h"
#include "scalar_generated.h"
*/
import "C"
import "errors"
import wago "github.com/wago-org/wago"

var commands = []command{
	{name: "vkAcquireNextImage2KHR", arity: 3, pointers: 6, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkAcquireNextImageKHR", arity: 6, pointers: 32, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkAllocateCommandBuffers", arity: 3, pointers: 6, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkAllocateDescriptorSets", arity: 3, pointers: 6, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkAllocateMemory", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkBeginCommandBuffer", arity: 2, pointers: 2, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkBindBufferMemory", arity: 4, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkBindBufferMemory},
	{name: "vkBindImageMemory", arity: 4, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkBindImageMemory},
	{name: "vkCmdBeginQuery", arity: 4, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}}, direct: direct_vkCmdBeginQuery},
	{name: "vkCmdBeginRenderPass", arity: 3, pointers: 2, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}}, direct: nil},
	{name: "vkCmdBindDescriptorSets", arity: 8, pointers: 160, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdBindIndexBuffer", arity: 4, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}}, direct: direct_vkCmdBindIndexBuffer},
	{name: "vkCmdBindPipeline", arity: 3, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64}}, direct: direct_vkCmdBindPipeline},
	{name: "vkCmdBindVertexBuffers", arity: 5, pointers: 24, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCmdBlitImage", arity: 8, pointers: 64, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI32}}, direct: nil},
	{name: "vkCmdClearAttachments", arity: 5, pointers: 20, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdClearColorImage", arity: 6, pointers: 40, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdClearDepthStencilImage", arity: 6, pointers: 40, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdCopyBuffer", arity: 5, pointers: 16, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdCopyBufferToImage", arity: 6, pointers: 32, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdCopyImage", arity: 7, pointers: 64, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdCopyImageToBuffer", arity: 6, pointers: 32, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdCopyQueryPoolResults", arity: 8, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}}, direct: direct_vkCmdCopyQueryPoolResults},
	{name: "vkCmdDispatch", arity: 4, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}}, direct: direct_vkCmdDispatch},
	{name: "vkCmdDispatchIndirect", arity: 3, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkCmdDispatchIndirect},
	{name: "vkCmdDraw", arity: 5, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}}, direct: direct_vkCmdDraw},
	{name: "vkCmdDrawIndexed", arity: 6, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}}, direct: direct_vkCmdDrawIndexed},
	{name: "vkCmdDrawIndexedIndirect", arity: 5, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}}, direct: direct_vkCmdDrawIndexedIndirect},
	{name: "vkCmdDrawIndirect", arity: 5, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}}, direct: direct_vkCmdDrawIndirect},
	{name: "vkCmdEndQuery", arity: 3, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}}, direct: direct_vkCmdEndQuery},
	{name: "vkCmdEndRenderPass", arity: 1, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64}, []wago.ValType{wago.ValI64}, []wago.ValType{wago.ValI64}}, direct: direct_vkCmdEndRenderPass},
	{name: "vkCmdExecuteCommands", arity: 3, pointers: 4, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdFillBuffer", arity: 5, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}}, direct: direct_vkCmdFillBuffer},
	{name: "vkCmdNextSubpass", arity: 2, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}}, direct: direct_vkCmdNextSubpass},
	{name: "vkCmdPipelineBarrier", arity: 10, pointers: 672, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdPushConstants", arity: 6, pointers: 32, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdResetEvent", arity: 3, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}}, direct: direct_vkCmdResetEvent},
	{name: "vkCmdResetQueryPool", arity: 4, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}}, direct: direct_vkCmdResetQueryPool},
	{name: "vkCmdResolveImage", arity: 7, pointers: 64, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdSetBlendConstants", arity: 2, pointers: 2, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCmdSetDepthBias", arity: 4, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValF32, wago.ValF32, wago.ValF32}, []wago.ValType{wago.ValI64, wago.ValF32, wago.ValF32, wago.ValF32}, []wago.ValType{wago.ValI64, wago.ValF32, wago.ValF32, wago.ValF32}}, direct: direct_vkCmdSetDepthBias},
	{name: "vkCmdSetDepthBounds", arity: 3, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValF32, wago.ValF32}, []wago.ValType{wago.ValI64, wago.ValF32, wago.ValF32}, []wago.ValType{wago.ValI64, wago.ValF32, wago.ValF32}}, direct: direct_vkCmdSetDepthBounds},
	{name: "vkCmdSetEvent", arity: 3, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}}, direct: direct_vkCmdSetEvent},
	{name: "vkCmdSetLineWidth", arity: 2, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValF32}, []wago.ValType{wago.ValI64, wago.ValF32}, []wago.ValType{wago.ValI64, wago.ValF32}}, direct: direct_vkCmdSetLineWidth},
	{name: "vkCmdSetScissor", arity: 4, pointers: 8, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdSetStencilCompareMask", arity: 3, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}}, direct: direct_vkCmdSetStencilCompareMask},
	{name: "vkCmdSetStencilReference", arity: 3, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}}, direct: direct_vkCmdSetStencilReference},
	{name: "vkCmdSetStencilWriteMask", arity: 3, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}}, direct: direct_vkCmdSetStencilWriteMask},
	{name: "vkCmdSetViewport", arity: 4, pointers: 8, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdUpdateBuffer", arity: 5, pointers: 16, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCmdWaitEvents", arity: 11, pointers: 1348, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCmdWriteTimestamp", arity: 4, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32}}, direct: direct_vkCmdWriteTimestamp},
	{name: "vkCreateBuffer", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateBufferView", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateCommandPool", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateComputePipelines", arity: 6, pointers: 40, allocators: 16, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateDescriptorPool", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateDescriptorSetLayout", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateDevice", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateEvent", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateFence", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateFramebuffer", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateGraphicsPipelines", arity: 6, pointers: 40, allocators: 16, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateImage", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateImageView", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateInstance", arity: 3, pointers: 5, allocators: 2, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreatePipelineCache", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreatePipelineLayout", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateQueryPool", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateRenderPass", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateSampler", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateSemaphore", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateShaderModule", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateSwapchainKHR", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkCreateXlibSurfaceKHR", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkDestroyBuffer", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyBuffer},
	{name: "vkDestroyBufferView", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyBufferView},
	{name: "vkDestroyCommandPool", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyCommandPool},
	{name: "vkDestroyDescriptorPool", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyDescriptorPool},
	{name: "vkDestroyDescriptorSetLayout", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyDescriptorSetLayout},
	{name: "vkDestroyDevice", arity: 2, pointers: 0, allocators: 2, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyDevice},
	{name: "vkDestroyEvent", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyEvent},
	{name: "vkDestroyFence", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyFence},
	{name: "vkDestroyFramebuffer", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyFramebuffer},
	{name: "vkDestroyImage", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyImage},
	{name: "vkDestroyImageView", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyImageView},
	{name: "vkDestroyInstance", arity: 2, pointers: 0, allocators: 2, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyInstance},
	{name: "vkDestroyPipeline", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyPipeline},
	{name: "vkDestroyPipelineCache", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyPipelineCache},
	{name: "vkDestroyPipelineLayout", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyPipelineLayout},
	{name: "vkDestroyQueryPool", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyQueryPool},
	{name: "vkDestroyRenderPass", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyRenderPass},
	{name: "vkDestroySampler", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroySampler},
	{name: "vkDestroySemaphore", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroySemaphore},
	{name: "vkDestroyShaderModule", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroyShaderModule},
	{name: "vkDestroySurfaceKHR", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroySurfaceKHR},
	{name: "vkDestroySwapchainKHR", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkDestroySwapchainKHR},
	{name: "vkDeviceWaitIdle", arity: 1, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64}, []wago.ValType{wago.ValI64}, []wago.ValType{wago.ValI64}}, direct: direct_vkDeviceWaitIdle},
	{name: "vkEndCommandBuffer", arity: 1, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64}, []wago.ValType{wago.ValI64}, []wago.ValType{wago.ValI64}}, direct: direct_vkEndCommandBuffer},
	{name: "vkEnumerateDeviceExtensionProperties", arity: 4, pointers: 14, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkEnumerateDeviceLayerProperties", arity: 3, pointers: 6, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkEnumerateInstanceExtensionProperties", arity: 3, pointers: 7, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkEnumerateInstanceLayerProperties", arity: 2, pointers: 3, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkEnumeratePhysicalDevices", arity: 3, pointers: 6, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkFlushMappedMemoryRanges", arity: 3, pointers: 4, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkFreeCommandBuffers", arity: 4, pointers: 8, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkFreeDescriptorSets", arity: 4, pointers: 8, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkFreeMemory", arity: 3, pointers: 0, allocators: 4, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: direct_vkFreeMemory},
	{name: "vkGetBufferMemoryRequirements", arity: 3, pointers: 4, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetDeviceGroupPresentCapabilitiesKHR", arity: 2, pointers: 2, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetDeviceGroupSurfacePresentModesKHR", arity: 3, pointers: 4, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetDeviceMemoryCommitment", arity: 3, pointers: 4, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetDeviceQueue", arity: 4, pointers: 8, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkGetEventStatus", arity: 2, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: direct_vkGetEventStatus},
	{name: "vkGetFenceStatus", arity: 2, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: direct_vkGetFenceStatus},
	{name: "vkGetImageMemoryRequirements", arity: 3, pointers: 4, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetImageSparseMemoryRequirements", arity: 4, pointers: 12, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetImageSubresourceLayout", arity: 4, pointers: 12, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceFeatures", arity: 2, pointers: 2, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceFormatProperties", arity: 3, pointers: 4, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceImageFormatProperties", arity: 7, pointers: 64, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceMemoryProperties", arity: 2, pointers: 2, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDevicePresentRectanglesKHR", arity: 4, pointers: 12, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceProperties", arity: 2, pointers: 2, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceQueueFamilyProperties", arity: 3, pointers: 6, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceSparseImageFormatProperties", arity: 8, pointers: 192, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceSurfaceCapabilitiesKHR", arity: 3, pointers: 4, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceSurfaceFormatsKHR", arity: 4, pointers: 12, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceSurfacePresentModesKHR", arity: 4, pointers: 12, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceSurfaceSupportKHR", arity: 4, pointers: 8, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetPhysicalDeviceXlibPresentationSupportKHR", arity: 4, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI64}}, direct: direct_vkGetPhysicalDeviceXlibPresentationSupportKHR},
	{name: "vkGetPipelineCacheData", arity: 4, pointers: 12, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetQueryPoolResults", arity: 8, pointers: 32, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32}}, direct: nil},
	{name: "vkGetRenderAreaGranularity", arity: 3, pointers: 4, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkGetSwapchainImagesKHR", arity: 4, pointers: 12, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkInvalidateMappedMemoryRanges", arity: 3, pointers: 4, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkMapMemory", arity: 6, pointers: 32, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkMergePipelineCaches", arity: 4, pointers: 8, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkQueueBindSparse", arity: 4, pointers: 4, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkQueuePresentKHR", arity: 2, pointers: 2, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkQueueSubmit", arity: 4, pointers: 4, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI64}}, direct: nil},
	{name: "vkQueueWaitIdle", arity: 1, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64}, []wago.ValType{wago.ValI64}, []wago.ValType{wago.ValI64}}, direct: direct_vkQueueWaitIdle},
	{name: "vkResetCommandBuffer", arity: 2, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32}}, direct: direct_vkResetCommandBuffer},
	{name: "vkResetCommandPool", arity: 3, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}}, direct: direct_vkResetCommandPool},
	{name: "vkResetDescriptorPool", arity: 3, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI32}}, direct: direct_vkResetDescriptorPool},
	{name: "vkResetEvent", arity: 2, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: direct_vkResetEvent},
	{name: "vkResetFences", arity: 3, pointers: 4, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkSetEvent", arity: 2, pointers: 0, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: direct_vkSetEvent},
	{name: "vkUnmapMemory", arity: 2, pointers: 0, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI64}}, direct: direct_vkUnmapMemory},
	{name: "vkUpdateDescriptorSets", arity: 5, pointers: 20, allocators: 0, result: voidResult, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkWaitForFences", arity: 5, pointers: 4, allocators: 0, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValI32, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32, wago.ValI64}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI64, wago.ValI32, wago.ValI64}}, direct: nil},
	{name: "vkCreateMetalSurfaceEXT", arity: 4, pointers: 10, allocators: 4, result: wago.ValI32, signatures: [3][]wago.ValType{[]wago.ValType{wago.ValI64, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32, wago.ValAnyRef, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI32, wago.ValI32, wago.ValI32}, []wago.ValType{wago.ValI64, wago.ValI64, wago.ValI64, wago.ValI64}}, direct: nil},
}

func direct_vkBindBufferMemory(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkBindBufferMemory(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]))))
}
func direct_vkBindImageMemory(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkBindImageMemory(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]))))
}
func direct_vkCmdBeginQuery(call wago.HostCall) {
	C.wv_direct_vkCmdBeginQuery(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]))
}
func direct_vkCmdBindIndexBuffer(call wago.HostCall) {
	C.wv_direct_vkCmdBindIndexBuffer(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]))
}
func direct_vkCmdBindPipeline(call wago.HostCall) {
	C.wv_direct_vkCmdBindPipeline(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkCmdCopyQueryPoolResults(call wago.HostCall) {
	C.wv_direct_vkCmdCopyQueryPoolResults(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]), C.uint64_t(call.ParamSlots()[4]), C.uint64_t(call.ParamSlots()[5]), C.uint64_t(call.ParamSlots()[6]), C.uint64_t(call.ParamSlots()[7]))
}
func direct_vkCmdDispatch(call wago.HostCall) {
	C.wv_direct_vkCmdDispatch(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]))
}
func direct_vkCmdDispatchIndirect(call wago.HostCall) {
	C.wv_direct_vkCmdDispatchIndirect(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkCmdDraw(call wago.HostCall) {
	C.wv_direct_vkCmdDraw(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]), C.uint64_t(call.ParamSlots()[4]))
}
func direct_vkCmdDrawIndexed(call wago.HostCall) {
	C.wv_direct_vkCmdDrawIndexed(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]), C.uint64_t(call.ParamSlots()[4]), C.uint64_t(call.ParamSlots()[5]))
}
func direct_vkCmdDrawIndexedIndirect(call wago.HostCall) {
	C.wv_direct_vkCmdDrawIndexedIndirect(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]), C.uint64_t(call.ParamSlots()[4]))
}
func direct_vkCmdDrawIndirect(call wago.HostCall) {
	C.wv_direct_vkCmdDrawIndirect(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]), C.uint64_t(call.ParamSlots()[4]))
}
func direct_vkCmdEndQuery(call wago.HostCall) {
	C.wv_direct_vkCmdEndQuery(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkCmdEndRenderPass(call wago.HostCall) {
	C.wv_direct_vkCmdEndRenderPass(C.uint64_t(call.ParamSlots()[0]))
}
func direct_vkCmdFillBuffer(call wago.HostCall) {
	C.wv_direct_vkCmdFillBuffer(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]), C.uint64_t(call.ParamSlots()[4]))
}
func direct_vkCmdNextSubpass(call wago.HostCall) {
	C.wv_direct_vkCmdNextSubpass(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]))
}
func direct_vkCmdResetEvent(call wago.HostCall) {
	C.wv_direct_vkCmdResetEvent(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkCmdResetQueryPool(call wago.HostCall) {
	C.wv_direct_vkCmdResetQueryPool(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]))
}
func direct_vkCmdSetDepthBias(call wago.HostCall) {
	C.wv_direct_vkCmdSetDepthBias(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]))
}
func direct_vkCmdSetDepthBounds(call wago.HostCall) {
	C.wv_direct_vkCmdSetDepthBounds(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkCmdSetEvent(call wago.HostCall) {
	C.wv_direct_vkCmdSetEvent(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkCmdSetLineWidth(call wago.HostCall) {
	C.wv_direct_vkCmdSetLineWidth(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]))
}
func direct_vkCmdSetStencilCompareMask(call wago.HostCall) {
	C.wv_direct_vkCmdSetStencilCompareMask(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkCmdSetStencilReference(call wago.HostCall) {
	C.wv_direct_vkCmdSetStencilReference(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkCmdSetStencilWriteMask(call wago.HostCall) {
	C.wv_direct_vkCmdSetStencilWriteMask(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkCmdWriteTimestamp(call wago.HostCall) {
	C.wv_direct_vkCmdWriteTimestamp(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]))
}
func direct_vkDestroyBuffer(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyBuffer(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyBufferView(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyBufferView(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyCommandPool(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyCommandPool(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyDescriptorPool(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyDescriptorPool(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyDescriptorSetLayout(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyDescriptorSetLayout(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyDevice(call wago.HostCall) {
	if call.ParamSlots()[1] != 0 || len(call.ParamSlots()) > 2 && uint32(call.ParamSlots()[2]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyDevice(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]))
}
func direct_vkDestroyEvent(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyEvent(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyFence(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyFence(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyFramebuffer(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyFramebuffer(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyImage(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyImage(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyImageView(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyImageView(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyInstance(call wago.HostCall) {
	if call.ParamSlots()[1] != 0 || len(call.ParamSlots()) > 2 && uint32(call.ParamSlots()[2]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyInstance(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]))
}
func direct_vkDestroyPipeline(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyPipeline(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyPipelineCache(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyPipelineCache(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyPipelineLayout(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyPipelineLayout(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyQueryPool(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyQueryPool(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyRenderPass(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyRenderPass(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroySampler(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroySampler(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroySemaphore(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroySemaphore(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroyShaderModule(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroyShaderModule(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroySurfaceKHR(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroySurfaceKHR(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDestroySwapchainKHR(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkDestroySwapchainKHR(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkDeviceWaitIdle(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkDeviceWaitIdle(C.uint64_t(call.ParamSlots()[0]))))
}
func direct_vkEndCommandBuffer(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkEndCommandBuffer(C.uint64_t(call.ParamSlots()[0]))))
}
func direct_vkFreeMemory(call wago.HostCall) {
	if call.ParamSlots()[2] != 0 || len(call.ParamSlots()) > 3 && uint32(call.ParamSlots()[3]) != 0 {
		trap(errors.New("guest Vulkan allocator callbacks are unsupported"))
	}
	C.wv_direct_vkFreeMemory(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))
}
func direct_vkGetEventStatus(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkGetEventStatus(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]))))
}
func direct_vkGetFenceStatus(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkGetFenceStatus(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]))))
}
func direct_vkGetPhysicalDeviceXlibPresentationSupportKHR(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkGetPhysicalDeviceXlibPresentationSupportKHR(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]), C.uint64_t(call.ParamSlots()[3]))))
}
func direct_vkQueueWaitIdle(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkQueueWaitIdle(C.uint64_t(call.ParamSlots()[0]))))
}
func direct_vkResetCommandBuffer(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkResetCommandBuffer(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]))))
}
func direct_vkResetCommandPool(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkResetCommandPool(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))))
}
func direct_vkResetDescriptorPool(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkResetDescriptorPool(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]), C.uint64_t(call.ParamSlots()[2]))))
}
func direct_vkResetEvent(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkResetEvent(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]))))
}
func direct_vkSetEvent(call wago.HostCall) {
	call.SetI32(0, int32(C.wv_direct_vkSetEvent(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]))))
}
func direct_vkUnmapMemory(call wago.HostCall) {
	C.wv_direct_vkUnmapMemory(C.uint64_t(call.ParamSlots()[0]), C.uint64_t(call.ParamSlots()[1]))
}
